openapi: 3.0.0
info:
  contact:
    email: support@example.com
    name: API Support
  description: Conductor backend API
  license:
    name: MIT
  termsOfService: https://example.com/terms/
  title: Conductor API
  version: "1.0"
paths: {}
